version: "3.7"
services:
  postgres:
    container_name: appsilon_database
    image: postgres
    env_file: .env
    ports:
      - 5432:5432
  backend:
    container_name: appsilon_backend
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - POSTGRES_HOST=appsilon_database
    ports:
      - 5000:5000
    volumes:
      - .:/app
